"""add user_id status and error_message to documents

Revision ID: 34c68b28c841
Revises: c7b3cd923558
Create Date: 2025-11-25 16:40:56.249534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c68b28c841'
down_revision = 'c7b3cd923558'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
